# Generated by Django 5.2.1 on 2025-08-16 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
            ],
            options={
                'unique_together': {('start_year', 'end_year')},
            },
        ),
        migrations.CreateModel(
            name='Monarch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200, null=True, blank=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('capital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monarchs', to='rulers.capital')),
            ],
            options={
                'unique_together': {('start_year', 'end_year')},
            },
        ),
    ]
